### ISSUE TITLE
Main Menu Doesn't Load

### ISSUE THREAD

**Issue by SW17CHBL4DE** [Galileo88/Galileos-Planet-Pack#16]
Can't wait to try your pack, if only the main menu would load :laughing: 

I have a clean install of KSP 1.3.0, no mods except GPP and Kopernicus. Not even GPP_Clouds for EVE or Scatterer.

Once I remove GPP from the GameData folder, the game loads and is playable. As soon as I run it with GPP it wont boot the Main Menu screen.

I've looked at the log and it seems like the issue is caused by Ceti and Iota textures not loading.

I have attached both GPP logs and non-GPP logs.

Hope this helps, itching to play! :smile: 

[KSP_Logs.zip](https://github.com/Galileo88/Galileos-Planet-Pack/files/1251069/KSP_Logs.zip)

**Comment by Poodmund** [comment]
Could you please reupload the KSP logs as it appears the .zip you attached is invalid. Alternatively you could post your logs on a site like PasteBin if you are having issues archiving the files.

Please refer to Sigma88's post in the KSP forums as to what logs are required to debug if you are unsure:  https://forum.kerbalspaceprogram.com/index.php?/topic/140580-130-122-kopernicus-release-5-august-17/&page=27#comment-2793409

**Comment by SW17CHBL4DE** [comment]
[KSP_Logs (2).zip](https://github.com/Galileo88/Galileos-Planet-Pack/files/1251129/KSP_Logs.2.zip)

**Comment by SW17CHBL4DE** [comment]
I hope that helps!

**Comment by theRagingIrishman** [comment]
Also just to confirm @SW17CHBL4DE , you did install the GPP_Textures right?

**Comment by SW17CHBL4DE** [comment]
Yes I certainly did, followed the install instructions directly.

Also an update; I tried installing Interstellar Adventure Extended (adds multiple orbiting star systems)
It didn't work initially because I had Kopernicus and ModuleFlight Intergrator separately installed with IA Extended.

Thankfully, IA-Extended has it's own Kopernicus, MFI bundled with it. I just used those files, and presto! It worked. Will copy those packaged files into a GPP enabled directory and see what happens

**Comment by SW17CHBL4DE** [comment]
Edit: I meant Interstellar Adventure Revived

**Comment by Poodmund** [comment]
Please ensure you are running Kopernicus 1.3.0-4 and the MFI it bundles when using GPP at this time: https://github.com/Kopernicus/Kopernicus/releases/tag/release-1.3.0-4

**Comment by SW17CHBL4DE** [comment]
Yeah. CKAN Kopernicus I had installed was 1.3.0-5. I'm now running 1.3.0-4 now it works.

Thanks for the quick replies guys!

**Comment by Poodmund** [comment]
Yeah the newer Kopernicus changed the way in how it instantiates the rings around bodies and it was causing KSP to crash hang as GPP is currently not updated for this new behaviour. The logs showed the issue was due to the rings so I made an educated guess. Glad it's all sorted now.
