### ISSUE TITLE
Would it be possible to provide CKAN enabled installation?

### ISSUE THREAD

**Issue by embix** [Galileo88/Galileos-Planet-Pack#17]
Hi, I use CKAN for years now and never looked back - because before then, I corrupted my installations on a weekly basis.

Would it be feasable (and legal? licensing stuff is nasty) to make it CKAN compatible and install all required dependencies in the right versions? 

BTW: Real Solar System did something comparable, so it at least seams doable.

**Comment by Galileo88** [comment]
RSS did not include the amount of capatibility and dependencies that GPP does. It's apples and oranges when comparing to RSS. We have been looking into CKAN for a while now, but the task is huge and complex. I don't see it happening any time soon to be honest.
