### ISSUE TITLE
1.3.1?

### ISSUE THREAD

**Issue by benoitpilighting** [Galileo88/Galileos-Planet-Pack#18]
Yes i am impatient... When is 1.3.1 support?

**Comment by JadeOfMaar** [comment]
I hope you're fully aware that this impatience will kill any mod of any size, including this one. (That's why there's a forum rule for it.) That said, our release will come when it comes. I say a week at most.

**Comment by benoitpilighting** [comment]
Woops sorry about this, i’m just a little bit too enthusiastic with this fantastic mod.
Thank you very much for your swift reply, have a great day !
Benoit

De : Jadon Wade [mailto:notifications@github.com]
Envoyé : samedi 7 octobre 2017 03:41
À : Galileo88/Galileos-Planet-Pack <Galileos-Planet-Pack@noreply.github.com>
Cc : Benoit BATAILLOU <benoit.bataillou@pi-lighting.com>; Author <author@noreply.github.com>
Objet : Re: [Galileo88/Galileos-Planet-Pack] 1.3.1? (#18)


I hope you're fully aware that this impatience will kill any mod of any size, including this one. (That's why there's a forum rule for it.) That said, our release will come when it comes. I say a week at most.

**Comment by JadeOfMaar** [comment]
Forgive me for any implied sourness in my response before I truncated it. I just wanted to affirm that you knew the risk with your post, but I'm also grateful that you came knocking. :)

**Comment by Galileo88** [comment]
OK, I see this was settled before I could bite any heads off... 😉 A release will come soon.
