### ISSUE TITLE
Ksc not part of kerbNet 

### ISSUE THREAD

**Issue by TenchuHawke** [Galileo88/Galileos-Planet-Pack#19]
I installed opm, gpp, and the mod so gpp is put outside the standard system (gpp extended?). Kerbal has no ksc on kerbNet, though there is a gsc. Theorizing that the kerbal relays didn't get moved.

**Comment by Galileo88** [comment]
Ill take a look. I think i know what the issue is.

**Comment by TenchuHawke** [comment]
Looks like all the launch locations are wrong.  One is in midair, one is underwater.  I suspect they are from Gael.  I accidentally switched from the KSP (Which doesn't have a launch pad icon) and can't switch back.  Any progress?

**Comment by Galileo88** [comment]
Everything should be fixed with the latest update.
