### ISSUE TITLE
GGP_Textures Folder Installed Incorrectly

### ISSUE THREAD

**Issue by mariohead** [Galileo88/Galileos-Planet-Pack#27]
Hi, I've downloaded the ZIP for the GPP_Textures Folder (3.0 for the Textures), and I have done so at least three times now, following all given directions precisely, yet I still load up the game to see a message saying that the GPP_Textures Folder Installed Incorrectly.

![gpptext1](https://user-images.githubusercontent.com/26550556/32699682-a062e458-c787-11e7-8286-3e721b9310e5.png)

![gpptext2](https://user-images.githubusercontent.com/26550556/32699686-ad48c4c6-c787-11e7-9eeb-539ec3cb956b.png)

**Comment by Sigma88** [comment]
you have installed the mod incorrectly, 
the correct way is to extract the "GPP" folder and put it in your GameData folder

then you extract GPP_Textures and put that folder inside of GPP

your address bar shows you have the files inside Galileos-Planet-Pack-master


you also downloaded the wrong archive, the correct one is found in the [releases](https://github.com/Galileo88/Galileos-Planet-Pack/releases) page

**Comment by Poodmund** [comment]
Also to add to the above, you can instantly tell the mod has not been installed correctly as the Main Menu shows the Kerbals orbiting Kerbin and not Gael. This is a telltale sign. To solidify what Sigma has said above, this should be your folder structure:

GPP Folder: "Kerbal Space Program\Game Data\GPP"
GPP Textures Folder: "Kerbal Space Program\GameData\GPP\GPP_Textures"
