### ISSUE TITLE
Add sattelite's rotational period in CelestialBodies.pdf

### ISSUE THREAD

**Issue by Zekario** [Galileo88/Galileos-Planet-Pack#28]
I assume that there are some that are not tidally locked, in which case it could be useful to include. If they *are* all tidally locked, a note would be helpful.
Grannus's SoI is also missing.
Does a 'day' count as 6 hours or 24 in the pdf? I assume 6.

**Comment by OhioBob** [comment]
All the moons are tidally locked except Agrippina and Julia.  So you are right, it probably does make sense to add the rotation periods.  A "day" is 6 hours.
