### ISSUE TITLE
Fix for Module Manager 3.0+

### ISSUE THREAD

**Issue by apowers** [Galileo88/Galileos-Planet-Pack#34]
Module Manage 3.0+ fixed an undocumented bug in how experiments are accessed in GPP_Science_Defaults.cfg (at least).
```
@EXPERIMENT_DEFINITION[*]
```
Should now be just
```
@EXPERIMENT_DEFINITION
```
https://forum.kerbalspaceprogram.com/index.php?/topic/50533-131-module-manager-301-dec-6th-2017-early-christmas-gift/&do=findComment&comment=3237686

**Comment by Galileo88** [comment]
Thank you. The changes have been made.
