### ISSUE TITLE
Linux 64bit visual problems

### ISSUE THREAD

**Issue by benzin1984** [Galileo88/Galileos-Planet-Pack#39]
This is a note of visual problems I've encountered in KSP 64bit Ubuntu, and the workarounds that worked for me. I don't know if it's something to be fixed in the main branch. Hopefully this note helps someone with similar problems.

Here's examples of what stars/rings/shadow parts of planets looked like, with a fresh install of **KSP 1.31** and **GPP 1.6.0.1**:
https://i.imgur.com/hakrAFQ.png
https://i.imgur.com/VPsNfAe.png
https://i.imgur.com/tp7nV0J.png

Main problem seems to be something to do with how .dds textures get loaded on Linux. Particularly where there's light shining through textures, or where textures get copied multiple times. I have tried many different config changes in GPP_Planets directory, tried re-saving .dds textures in Gimp with dds addon. In the end, what worked for me was saving the problematic textures as .png, and re-pointing the .cfg files to use these .png textures. Except for the GPP/terrain/gradient.dds files, these worked when I re-saved them in Gimp with rgb8/dxt5 compression. I've put together a zip file with modified files. I haven't tested it yet with EVE/scatterer etc, but no reason why this wouldn't work. Here's a link to the zip file: `https://www.dropbox.com/s/[CENSORED]/GPP.tar.gz`

**Comment by Sigma88** [comment]
hi, I don't think GPP license allows the redistribution of modified assets,

just to be on the safe side I removed your link and sent it privately to Galileo so he can take a look and see if he can use the information to fix GPP

or alternatively he can decide to give you permission to share :)

thanks for the report and for the tests! they are much apreciated

**Comment by Sigma88** [comment]
I believe this issue was solved by the latest kopernicus

I think we can close it
