### ISSUE TITLE
Missing Biomes for GPP Secondary

### ISSUE THREAD

**Issue by TenchuHawke** [Galileo88/Galileos-Planet-Pack#41]
I did a fresh install, ran the game, installed Kopernicus, ran the game, installed GPP and GPP secondary (And their required dependencies) ran the game.

The first time I ran it (Vanilla) - Mun has biomes.
The second time I ran it (Kopernicus) - Mun has biomes.
Last time I ran it(GPP, GPP Sec) - No biomes.  When I try to do an EVA Report the console shows the following error: 

[Experiments]:  Setting FX Modules to 1...
[Experiments]: FX Modules set: 1
Exception:  IndexOutOfRangeException: Array Index is out of range.

**Comment by Sigma88** [comment]
this is a known issue, you can follow the discussion and find a solution here:

https://github.com/Kopernicus/Kopernicus/issues/272

**Comment by TenchuHawke** [comment]
Thanks for the heads up.
