### ISSUE TITLE
Soft Lock in menu with KerbalKonstructs installed

### ISSUE THREAD

**Issue by T10a** [Galileo88/Galileos-Planet-Pack#45]
Issue: Soft lock when I attempt to click on anything after clicking on Start Game.
Mods installed:

- Galileo Planet Pack
- GPP Textures
- KerbalKonstructs
- KKtoSD
- Kopernicus
- ModularFlightIntegrator
- ModuleManager
- MusicMute (Tested without this, just to hide the music while testing)
- RESCALE 2.5x
- SigmaBinary
- SigmaDimensions

Log file here (log is too big for Pastebin, so I only got the Menu part): https://pastebin.com/SJ4GZL2q

**Comment by GER-Space** [comment]
You should attach the complete logfile here directly. I cannot see any reason there is a error

**Comment by T10a** [comment]
Here's the full thing (about 1 megabytes): https://www.dropbox.com/s/yobpcxyf04n56aj/KSP.log?dl=0

**Comment by T10a** [comment]
And as requested on Discord, here's the log file: https://www.dropbox.com/s/gdmhetrgtpezclg/KSP.log?dl=0

**Comment by T10a** [comment]
Somehow, this issue fixed itself. I do not know how, but I'm closing this.
