### ISSUE TITLE
Reentry effects turning oceans red on Gael

### ISSUE THREAD

**Issue by Tuupertunut** [Galileo88/Galileos-Planet-Pack#47]
**KSP version:** 1.4.3.2152
**GPP version:** 1.6.3.0
**Other mods:** No other mods than GPP and its dependencies.

#### Description:
When a vessel is experiencing reentry effects, the oceans of Gael will turn red with a bright red spot somewhere, kind of like a sun reflection. This does not happen on Kerbin in stock game.

![screenshot1](https://user-images.githubusercontent.com/1782631/41511289-c37f6560-727c-11e8-800c-c19d5e9724e6.png)

#### How to reproduce:
Launch a rocket from the space center towards east at high speed in low atmosphere and you will see it as soon as reentry effects start.

[output_log.txt](https://github.com/Galileo88/Galileos-Planet-Pack/files/2109314/output_log.txt)

**Comment by EndIris** [comment]
I've seen this also. It doesn't happen with all planet mods, so it's something with GPP. Hoping someone looks into this.

**Comment by Galileo88** [comment]
It does happen with other planet mods. Its been confirmed by the kopernicus devs and other planet modders. A fix is not in the works as of right now.

**Comment by Tuupertunut** [comment]
Can you link to a kopernicus issue so we can track the progress.

**Comment by Tuupertunut** [comment]
I still don't know about any mention of this bug from kopernicus devs, so this issue is the only handle I have. Is there any progress?

**Comment by eberkain** [comment]
It seems to also have something to do with the sun angle because I only get the effect on some launches and some reentries.
