### ISSUE TITLE
Strategia Patch deletes all contracts

### ISSUE THREAD

**Issue by CaesarVincens** [Galileo88/Galileos-Planet-Pack#7]
The file GPP_Strategia.cfg deletes any Contract Configurator type contract with the line `!CONTRACT_TYPE:HAS[~protectedStrategy[true]]:FOR[GPP] {}` which is meant to target the Strategia contracts but is not limited to them.

**Comment by Darael** [comment]
Would it not make more sense to use `:HAS[#group[Strategia],~protectedStrategy[true]]`?  That ought to limit the effect to those that are both in the Strategia group *and* not flagged as protected.

**Comment by CaesarVincens** [comment]
I'm not familiar with the Contract Config syntax, but that looks better.

**Comment by Poodmund** [comment]
With the latest upcoming patches and the changes Nightingale has made to Strategia, I think I can call this issue solved and closed.
