### ISSUE TITLE
Support stock PQSCities from Kerbin

### ISSUE THREAD

**Issue by eberkain** [Galileo88/Galileos-Planet-Pack#8]
Some mods like Kerbal Academy contract pack [rely on PQSCities from the stock kerbin](https://github.com/severedsolo/KerbalAcademy/issues/6), like the island runway.   Would it be possible to add these somewhere on Gael so when other mods look for them it doesn't throw errors?  I ask the question not knowing how many there are or how much work this involves, so please don't shoot me.   Or would the better solution be to just have other mods that encounter these problems to add support specific to GPP?

**Comment by Poodmund** [comment]
Well from SeveredSolo's comment it doesn't seem like they're interested in making allowances for GPP as a specific compatibility patch. Do you happen to know what PQSCities are required in total?

**Comment by Galileo88** [comment]
they will have to add support themselves. Thats more work than i care to get into

**Comment by eberkain** [comment]
I downloaded the Kerbal Academy contract pack and did a file contents search for "pqsCity" and I got 3 hits

BootCamp.cfg
pqsCity = IslandAirfield  //used in waypoint generation
pqsCity = KSC   //used to spawn a vessel I think

FlightSchool.cfg
pqsCity = KSC  //used to generate a waypoint

**Comment by Galileo88** [comment]
His should be fixed in the latest release. All stock pqs city items are now available.
